# Generated by Django 4.0.2 on 2023-07-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("birth", models.DateField(max_length=8)),
                (
                    "sex",
                    models.CharField(
                        choices=[("FEMALE", "F"), ("MALE", "M")], max_length=6
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customeremail",
                        to="crudapp.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=30)),
                ("province", models.CharField(max_length=30)),
                ("street", models.CharField(max_length=30)),
                ("postcode", models.CharField(max_length=10)),
                ("house", models.CharField(max_length=6)),
                ("flat", models.CharField(max_length=4)),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customeraddress",
                        to="crudapp.customer",
                    ),
                ),
            ],
        ),
    ]
