# Generated by Django 4.0.2 on 2023-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="birth",
            field=models.DateField(max_length=10),
        ),
    ]
