# Generated by Django 4.0.2 on 2023-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0002_alter_customer_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="flat",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="house",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
