# Generated by Django 4.0.2 on 2023-07-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0003_alter_address_flat_alter_address_house_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crudapp.customer",
            ),
        ),
        migrations.AlterField(
            model_name="emailphone",
            name="person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crudapp.customer",
            ),
        ),
    ]
